import { GateVerdict, SpecDocument, SpecTask } from '../types';

/**
 * Deterministic PR title/body for a task branch (P3 T-02). Pure functions
 * of the spec task, run identity, and any verdicts recorded so far — the
 * same inputs always produce the same PR text, so resume-created and
 * first-run PRs are indistinguishable.
 */
export const prTitle = (runId: string, task: SpecTask): string =>
  `sdlc(${runId}): ${task.id} ${task.title}`;

const TEST_TIER_PREFIX = /^test:\s*/;

/**
 * Deliberately not a full {@link parseAllCriteria} call: `prBody` is a pure
 * render function that must never throw on a spec a human is actively
 * reviewing, so this only ever adds an informational note and silently
 * adds nothing for criteria that don't match the simple prefix check.
 */
const countTestTierCriteria = (criteria: string[]): number =>
  criteria.filter(criterion => TEST_TIER_PREFIX.test(criterion.trim())).length;

export const prBody = (
  spec: SpecDocument,
  task: SpecTask,
  runId: string,
  branch: string,
  verdicts: GateVerdict[]
): string => {
  const lines: string[] = [
    '## Summary',
    '',
    `Machine-generated implementation of **${task.id} — ${task.title}**`,
    `from spec \`${spec.id}\` (${spec.prdId}, phase ${spec.phase}).`,
    '',
    `- Run: \`${runId}\``,
    `- Branch: \`${branch}\``,
    `- Story: ${task.storyId} · Complexity: ${task.complexity}` +
      (task.dependsOn.length > 0
        ? ` · Depends on: ${task.dependsOn.join(', ')}`
        : ''),
    '',
    '## Acceptance criteria',
    ''
  ];
  for (const criterion of task.acceptanceCriteria) {
    lines.push(`- ${criterion}`);
  }
  const testTierCount = countTestTierCriteria(task.acceptanceCriteria);
  if (testTierCount > 1) {
    lines.push(
      '',
      `> All ${testTierCount} \`test:\` criteria above share **one** run of ` +
        'the repo\'s scripted verify command — they are not independently ' +
        'asserted. If a specific behavior needs its own guarantee, a real ' +
        'test for it must exist in the repo.'
    );
  }

  lines.push('', '## Gate verdicts');
  if (verdicts.length === 0) {
    lines.push(
      '',
      '_Recorded after the machine gates run; see the run Chronicle artifacts._'
    );
  } else {
    lines.push('');
    for (const verdict of verdicts) {
      lines.push(
        `- ${verdict.gate}: **${verdict.outcome}**` +
          (verdict.reasons.length > 0 ? ` — ${verdict.reasons.join('; ')}` : '')
      );
    }
  }

  lines.push(
    '',
    '---',
    `Generated by sdlc-workflow (PRD-0011 Phase 3) · run \`${runId}\` · task \`${task.id}\``
  );
  return lines.join('\n');
};
