export const WORKFLOW_TOKENS = {
  ModelRepository: Symbol.for('ModelRepository'),
  InferenceRepository: Symbol.for('InferenceRepository'),
  PrdRepository: Symbol.for('PrdRepository'),
  SpecFileRepository: Symbol.for('SpecFileRepository'),
  DecomposeService: Symbol.for('DecomposeService'),
  SpecSynthesisService: Symbol.for('SpecSynthesisService'),
  WorkflowHandler: Symbol.for('WorkflowHandler'),
  // SPEC-PRD-0011-P2
  SpecDocRepository: Symbol.for('SpecDocRepository'),
  GitRepository: Symbol.for('GitRepository'),
  AgentRunnerRepository: Symbol.for('AgentRunnerRepository'),
  RunStateRepository: Symbol.for('RunStateRepository'),
  RunLockRepository: Symbol.for('RunLockRepository'),
  SurfaceMapRepository: Symbol.for('SurfaceMapRepository'),
  ReviewChecklistRepository: Symbol.for('ReviewChecklistRepository'),
  ContractRepository: Symbol.for('ContractRepository'),
  ShellCommandRepository: Symbol.for('ShellCommandRepository'),
  EvidenceRepository: Symbol.for('EvidenceRepository'),
  QueueRepository: Symbol.for('QueueRepository'),
  ChronicleArtifactRepository: Symbol.for('ChronicleArtifactRepository'),
  CiStatusRepository: Symbol.for('CiStatusRepository'),
  ExecutorService: Symbol.for('ExecutorService'),
  EnvelopeGateService: Symbol.for('EnvelopeGateService'),
  SandboxDeployService: Symbol.for('SandboxDeployService'),
  VerificationService: Symbol.for('VerificationService'),
  ReviewerGateService: Symbol.for('ReviewerGateService'),
  ReviewerPublishService: Symbol.for('ReviewerPublishService'),
  AggregatorService: Symbol.for('AggregatorService'),
  CiGateService: Symbol.for('CiGateService'),
  DigestService: Symbol.for('DigestService'),
  RetroService: Symbol.for('RetroService'),
  ChronicleCommitService: Symbol.for('ChronicleCommitService'),
  GatePolicyQueryService: Symbol.for('GatePolicyQueryService'),
  RunHandler: Symbol.for('RunHandler'),
  // SPEC-PRD-0011-P3
  PullRequestRepository: Symbol.for('PullRequestRepository'),
  IssueRepository: Symbol.for('IssueRepository'),
  WakeInboxRepository: Symbol.for('WakeInboxRepository'),
  PrLifecycleService: Symbol.for('PrLifecycleService'),
  EscalationService: Symbol.for('EscalationService'),
  GateRemediationService: Symbol.for('GateRemediationService'),
  RetryExecutorService: Symbol.for('RetryExecutorService'),
  HeartbeatService: Symbol.for('HeartbeatService'),
  HeartbeatWatchService: Symbol.for('HeartbeatWatchService'),
  ProcessDetachRepository: Symbol.for('ProcessDetachRepository'),
  SuperviseExitRepository: Symbol.for('SuperviseExitRepository'),
  SuperviseService: Symbol.for('SuperviseService'),
  // SPEC-BUG-retro-and-queued-plans T-02
  RunQueueRepository: Symbol.for('RunQueueRepository'),
  // SPEC-PRD-0022-P1 T-01
  DeployRecordRepository: Symbol.for('DeployRecordRepository'),
  // SPEC-PRD-0023-P1 T-01 / T-02
  CloseoutAggregateService: Symbol.for('CloseoutAggregateService'),
  CloseoutService: Symbol.for('CloseoutService'),
  // SPEC-PRD-0020-P1 T-01
  DaemonConfigRepository: Symbol.for('DaemonConfigRepository'),
  DaemonProcessRepository: Symbol.for('DaemonProcessRepository'),
  LaunchdRepository: Symbol.for('LaunchdRepository'),
  DaemonLifecycleService: Symbol.for('DaemonLifecycleService'),
  DaemonHandler: Symbol.for('DaemonHandler'),
  // SPEC-PRD-0020-P1 T-02
  DaemonStoreRepository: Symbol.for('DaemonStoreRepository'),
  // SPEC-PRD-0020-P1 T-03
  WatchRegistryService: Symbol.for('WatchRegistryService'),
  // PRD-0026
  DropStateRepository: Symbol.for('DropStateRepository'),
  DropService: Symbol.for('DropService'),
  DropHandler: Symbol.for('DropHandler')
} as const;
